services:
  postgres:
    image: postgres:14.13-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pos_inventory
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql